### ISSUE TITLE
Unit tests fail under windows 

### ISSUE THREAD

**Issue by stoewer** [G-Node/nix#427]
The unit tests of the current version fail under windows.

Failing tests:
- [x] TestDataSet
- [x] TestFile
- [x] TestGroup
- [x] TestMultiTag
- [x] TestProperty
- [x] TestValidate

More details [here](https://ci.appveyor.com/project/stoewer/nix/build/0.11.19).

**Comment by gicmo** [comment]
Fixed with pr #446 & pr #447 together with using the pre-compiled hdf5 dlls from the HDF5 Group website.
