### ISSUE TITLE
[win] build warnings

### ISSUE THREAD

**Issue by gicmo** [G-Node/nix#447]
There are [currently (build 0.11.53)](https://ci.appveyor.com/project/stoewer/nix/build/0.11.53) 77 build warnings. Should be zero.

**Comment by gicmo** [comment]
Depends on #465 because if any file includes anything that includes xutiltiy on windows, we cannot disable the warnings with pragmas.

**Comment by gicmo** [comment]
Lot of the remaining warnings are actually `LNK4099` because we lack the debug symbols file for cppunit in our nix-dependencies.

**Comment by jgrewe** [comment]
this issue can be closed. It seems there are more appveyor windows build warnings
