### ISSUE TITLE
Include directives cleanup

### ISSUE THREAD

**Issue by gicmo** [G-Node/nix#465]
In order to avoid any latent dependencies I would suggest that in all files (header, implementation) we first include project files, and then system/global headers. And in implementation files the very first include should be the corresponding header file, i.e. DataSet.cpp should include DataSet.hpp as the first include.

**Comment by jgrewe** [comment]
This issue seems to be resolved with pr #466, isn't it?

**Comment by gicmo** [comment]
Yes!
