### ISSUE TITLE
Open non existing file in file mode ReadOnly

### ISSUE THREAD

**Issue by mpsonntag** [G-Node/nix#490]
If a nix file is opened with FileMode ReadOnly and this file actually does not exist, then a new file with the provided path/name will be created and a handle will be returned with FileMode Overwrite.

This behavior lead to the acutal case, that someone wanted to open an existing file in ReadOnly mode, but provided an incorrect path where the file of course did not exists. A new file was created in Overwrite mode and the user was perplexed to find a completly empty file where there should have been blocks eau masse.

This use case raises the question, if the current behavior should be changed or at least amended. 

Possible changes could be:
- do not allow to create a new file, if the mode is ReadOnly
- provide notification message, whenever a new file is created

**Comment by jgrewe** [comment]
this issue has been solved with pr #615
