### ISSUE TITLE
Build broken with boost 1.58.0

### ISSUE THREAD

**Issue by gicmo** [G-Node/nix#504]
Starting with boost [1.58.0](http://www.boost.org/users/history/version_1_58_0.html) it is not possible to convert between `std::nullptr` and `boost::none_t`: 
> boost::none_t is no longer convertible from literal 0. This avoids a bug where `optional<rational<int>> oi = 0;` would initialize an optional object with no contained value.

Since we have code in the test that indirectly use that feature, the build is broken with boost >= 1.58.0

**Comment by jgrewe** [comment]
this issue is resolved with pr #505, isn't it?

**Comment by gicmo** [comment]
@jgrewe yes, closing.
