### ISSUE TITLE
Logo and web site

### ISSUE THREAD

**Issue by stoewer** [G-Node/nix#527]
Integrate the new NIX logo into documentation sites and tutorials.

Create a nix web site.

**Comment by jgrewe** [comment]
Btw., what do you think of the new designs? Once we decide on something, he will finalize it and send the vector graphics

**Comment by jgrewe** [comment]
I guess this issue can be closed. Tutorials and stuff are on the http://g-node.github.io/nix/ sites.
If more is needed, we can collect this in a new issue.
