### ISSUE TITLE
License must be changed to e.g. BSD-3

### ISSUE THREAD

**Issue by yarikoptic** [G-Node/nix#542]
BSD-4 used by the project ATM is not even compatible with GPL (and probably other copyleft licenses) due to inclusion of the advertisement clause (#3).  Such BSD licenses were dropped even by original users of them, see http://www.gnu.org/licenses/license-list.en.html#OriginalBSD

**Comment by gicmo** [comment]
I guess BSD-4 this was a poor choice then because we clearly don't want to be incompatible with GPL. I guess the closest alternative would be [Modified BSD](http://www.gnu.org/licenses/license-list.en.html#ModifiedBSD), unless someone else has a better idea.

**Comment by gicmo** [comment]
We should fix this for 1.1.

**Comment by jgrewe** [comment]
No objection, neither against, the version 1.1, nor the modified BSD

**Comment by stoewer** [comment]
Also no objections from my side. I was not aware of the incompatibility issues between BSD 4-clause and GPL. Here is a good summary of GPL compatible and incompatible licenses:

https://www.gnu.org/licenses/license-list.en.html

I also think the modified BSD (3-clause) license would be a good choice. The above site further suggests Apache 2 as an alternative.

**Comment by stoewer** [comment]
Maybe we should use this opportunity to update the copyright holder list in the head of our license file.

**Comment by balint42** [comment]
I think that BSD (3-clause) seems totally valid! Yes to BSD 3. :-)

**Comment by stoewer** [comment]
In our source files we have quite a mix of copyright and author declarations. In most of the files, even those with contributions from many authors, we have just the following copyright notice:

```c
// Copyright (c) 2013, German Neuroinformatics Node (G-Node)
...
```

In some others we have multiple copyright holders such as:

```c
// Copyright © 2015 German Neuroinformatics Node (G-Node)
//                  John Doe <john.doe@example.org>
...
```

To make it even more diverse we also have headers like this:

```c
// Copyright © 2015 German Neuroinformatics Node (G-Node)
...
// Author: John Doe <john.doe@example.org>
```

If we change our license it might be a good idea to unify our license headers too. In other projects I have seen something like this:

```c
// Copyright © 2015 German Neuroinformatics Node (G-Node),
//                  Contributors as listed in Contributors.md
...
```

The `Contributors.md` file contains a list of all contributors with name and mail address. IMHO this is a very practical way to acknowledge all contributions (and the inherent moral rights of authors).

* Is such a copyright delegation to a contributors file legally OK?
* Do the main developers agree to be acknowledged in the same way as  occasional contributors?

**Comment by gicmo** [comment]
IANAL but in Germany copyright is not transferable ([wikipedia](https://en.wikipedia.org/wiki/Copyright_law_of_Germany)), so I guess technically that "(c) G-Node" is nonsense; also since people always retain their copyright, maybe we have to list the main authors of every file (c) bit?

**Comment by stoewer** [comment]
> IANAL but in Germany copyright is not transferable (wikipedia), so I guess technically that "(c) G-Node" is nonsense; 

AFAIK copyright is transferable but moral rights (Urheberrechte) are not, therefore putting G-Node there should be valid (not saying that it must be there).

> also since people always retain their copyright, maybe we have to list the main authors of every file (c) bit?

Ideally yes. However, given the fact that in most files actually no main contributor is currently listed as copyright holder, I worry that such a system will not be maintained. In addition we would actually need to figure out who the main contributors are and put them in the authors list in the first place.
