### ISSUE TITLE
Evaluate NuGet packages for Windows builds

### ISSUE THREAD

**Issue by stoewer** [G-Node/nix#547]
Currently we use our custom build dependencies for NIX windows builds. Maybe it is worth evaluating the whether dependencies can be installed with NuGet:

https://www.nuget.org/packages/hdf5-v120/
https://www.nuget.org/packages/boost/
https://www.nuget.org/packages/cppunit/
https://www.nuget.org/packages/gtest/

**Comment by gicmo** [comment]
Turnout that this is not really what we want ;(
