### ISSUE TITLE
reduce unused odml values 

### ISSUE THREAD

**Issue by jgrewe** [G-Node/nix#550]

**Comment by gicmo** [comment]
What can go? 
- [ ] `reference` 
- [ ] `filename`
- [ ] `encoder`
- [ ] `checksum`

All of it? :)

**Comment by jgrewe** [comment]
yes, I think so. 
the first i have never seen  being used, the latter, are all related to the binary stuff...

**Comment by gicmo** [comment]
Do we want this for 1.5?
