### ISSUE TITLE
Backend code separation

### ISSUE THREAD

**Issue by gicmo** [G-Node/nix#584]
Currently the backend code is intertwined with the fronted code, everything living in `src`, i.e. the hdf5 backend is in `src/hdf5` and the headers are in `include/nix/hdf5` (and are also installed). With pull request #583 the hdf5 backend headers are not installed anymore (along with the separation of hdf5 backend code from the h5 C++ wrapper). The file backend currently lives in `src/file` 
It would be cleaner if all the backends all the backends would live in `backend/[name]` (instead of `src/[name]`).

**Comment by stoewer** [comment]
Sounds good :+1:

**Comment by jgrewe** [comment]
closed via pr #583

**Comment by jgrewe** [comment]
ups, not yet entirely done...

**Comment by jgrewe** [comment]
I wonder whether we should keep the HDF5, FS suffixes in our backend naming scheme. They may help to distinguish between back  and front ends but it looks like done twice...

**Comment by jgrewe** [comment]
apparently finalized with pr #604 #603
