### ISSUE TITLE
Naming: keep NIX for the project, use "nixio" for the libraries

### ISSUE THREAD

**Issue by gicmo** [G-Node/nix#595]
We currently have:
- NIX (C++)
  - homebrew science: `nixio`
- NixPy Python:
  -   PyPI: `nixpy` (?)

The idea would be to use `nixio` for all libraries to unify naming.

**Comment by stoewer** [comment]
Agreed

**Comment by jgrewe** [comment]
does that also mean that we change the names of the library?

libnix -> libnixio
import nixio
etc...

**Comment by stoewer** [comment]
From my point of view this should definitely apply to:

* library names (so, dll, jar etc)
* package names (Debian, PyPi, homebrew)
* python package names (e.g. from nixio import File ...)

Optionally we can also change:

* C++ namespaces
* Main header (nix.hpp -> nixio.hpp)

**Comment by jgrewe** [comment]
I am not sure about the namespaces but probably the header.
The project name itself will remain unchanged, correct?

**Comment by stoewer** [comment]
Yes, the project and repository name(s) should remain unchanged

**Comment by gicmo** [comment]
I think we should be done here, or can anybody think of anything else?
