### ISSUE TITLE
Shape of Data Array does not change in nixview if file containing the Array is altered

### ISSUE THREAD

**Issue by DennisHub** [G-Node/nix#614]
To reproduce: Save data array of length k in file. Run the program again and save a different data array of the same name and length l in the same file. Open file with nixview.
If l>k: You'll find the second array cut off at length k.
If l<k: You'll find various values (0, nan, very large and very small numbers) at the end of the array.

Temporary fix is deleting the file. This is most likely not an issue with how the data is saved, because HDFview gives the correct shape.

**Comment by jgrewe** [comment]
I was able to reproduce this error when editing the file while opened in nix view. The information in the file  is correct so it is not a nix issue and hence I move this issue to nix view.
