### ISSUE TITLE
Use ndsize_t for function dimension related arguments 

### ISSUE THREAD

**Issue by gicmo** [G-Node/nix#628]
Follow up to issue #473, and related to G-Node/nix-mx#114

- [x] `SampledDimension::axis(const size_t count, const size_t startIndex = 0)`
- [x] `RangeDimension::axis(const size_t count, const size_t startIndex = 0)`
- [x] `SampledDimension::positionAt(const size_t index) const`
- [x] `SampledDimension::operator[](const size_t index)`
- [x] `RangeDimension::operator[](const size_t index)`
- [x] `RangeDimension::tickAt(const size_t index) const`

**Comment by gicmo** [comment]
PR #629 a few checks that are not really necessary. I.e. src/Dimensions.cpp line 192. We really only need to make that check if we need a `size_t`, e.g. for creating a `std::vector` or accessing elements in a vector.
We should also create tests for arrays that are bigger then 32 bits in size to check if the code actually works. ;)

**Comment by jgrewe** [comment]
closed via #632
