### ISSUE TITLE
Tag/Multitag hasFeature(name) and getFeature(name) do not work properly

### ISSUE THREAD

**Issue by jgrewe** [G-Node/nix#650]

**Comment by jgrewe** [comment]
Actually this is no bug but a "non-feature", i.e. the method is only supposed to take an id. In case one passes a name, it does not complain but also does not return a thing. One wonders, if we should add searching by name.

**Comment by achilleas-k** [comment]
It would be nice to support retrieval by name. I think it someone might expect that it would work since retrieving items by name in addition to ID is common throughout the library.
