### ISSUE TITLE
Adding Wiki for easy understanding of NIX project

### ISSUE THREAD

**Issue by s0nskar** [G-Node/nix#667]
I'm not complaining, but I think NIX project current documentation lacks a lot and I think everyone aware of it. I know adding documentation support for the whole project is quite a daunting task. But least we can do is add a Wiki explaining what each directory contains, what each classes are used for. Even adding a liitle paragraph for description for each will made the life of contributor easy.

**Comment by jgrewe** [comment]
you did notice the existing [wiki](https://github.com/G-Node/nix/wiki) ;)

**Comment by s0nskar** [comment]
I saw that already. But the wiki you mentioned, according to me that only provide like frontend side description like It does not throw any light on implementation containers. What I want to say, we should add something like this http://g-node.github.io/nix/annotated.html or complete this list. It still lacks many directory/classes definition like what `backend/fs` and  `backend/hdf5` are for?

**Comment by achilleas-k** [comment]
So you mean a developer guide/wiki? Something to help people who want to contribute or develop NIX, instead of a wiki for users.

**Comment by msuzen** [comment]
@s0nskar Doxygen is pretty good at catching patterns by producing browsable hierarchy. Did you mean more inline comments?

**Comment by jgrewe** [comment]
more introductory material and tutorial now available [here](https://g-node.github.io/nix).
