### ISSUE TITLE
Appending objects to groups should not use ID getters

### ISSUE THREAD

**Issue by achilleas-k** [G-Node/nix#673]
The append methods for the Group object should not use IDs for retrieving objects from the parent block. Using the ID to check if the object exists and for retrieving it for append causes the operation to become slower as the number of objects increases.

Ideally, if an object is provided to the `add` method, its name should be used to retrieve the object from the parent block and the ID should be compared to make sure it is the same object. This is similar to how `dataArrays()` appends multiple items, but we should also include an ID comparison (see #672).

**Comment by jgrewe** [comment]
solved via #679
