### ISSUE TITLE
1.4.1 Release

### ISSUE THREAD

**Issue by gicmo** [G-Node/nix#701]
We make a new stable release, after backporting some changes to the 1.4 branch, like:
 - PR #700 
 - PR #698 
 - PR #697 

Something else?

**Comment by jgrewe** [comment]
would like to add the unit handling to it, i.e. allow non-SI in metadata  and maybe also for DataArray values but not dimensions, positions and extents. (Will be ugly for AliasRange dimensions, but this will then simply lead to an exception)

**Comment by gicmo** [comment]
I wouldnt be against it. Could also be 1.5 material. Fine either way with me.

**Comment by jgrewe** [comment]
is there urgent demand?

**Comment by jgrewe** [comment]
done
