### ISSUE TITLE
Homebrew/science is no longer available

### ISSUE THREAD

**Issue by jgrewe** [G-Node/nix#720]
Since late December homebrew/science is deprecated and is no longer part of homebrew. That means, that the installation via ```brew``` does not work.

**Comment by achilleas-k** [comment]
Looks like it was migrated to [brewsci/homebrew-science](https://github.com/brewsci/homebrew-science/blob/master/Formula/nixio.rb). It works, but it's unmaintained. Should we submit to core?

**Comment by jgrewe** [comment]
homebrew formulae will be maintained in https://github.com/g-node/homebrew-pkg repo
