### ISSUE TITLE
concurrent reads on a file unsafe

### ISSUE THREAD

**Issue by Nyxas** [G-Node/nix#725]
There is a way to built HDF5-lib in thread-safe mode, which allows concurrent reads but that is only for C officially supported.
https://portal.hdfgroup.org/display/knowledge/Questions+about+thread-safety+and+concurrent+access

**Comment by achilleas-k** [comment]
Wait, concurrent **reads** are unsafe?
The linked FAQ says
> Does HDF5 support concurrent access to a single dataset from multiple processes?
> If all processes are reading, then, yes, HDF5 (serial) does support this.

**Comment by gicmo** [comment]
NB: we are not using the official C++ bindings, but have our own version. They are a thin layer on top of the C library and I don't think they are done in a non-thread-safe way; but I am not 100% sure. They would need to be checked.

**Comment by achilleas-k** [comment]
Doesn't everything use the core C library at the end of the day (h5py included)?

**Comment by gicmo** [comment]
@achilleas-k sure, but in the C++ one could cache/re-use handles or what not that makes it non-thread safe/aware.

**Comment by achilleas-k** [comment]
@gicmo Good point. Had not considered.

Back to the original issue: Are concurrent **reads** unsafe?

**Comment by gicmo** [comment]
I don't think so, I can't think of something funny we do, that would make them. @Nyxas you have any indication of reads being a problem? Crashes?

**Comment by Nyxas** [comment]
In nixview i'm currently building a way to load more data for plots and for that i'm using a second thread.
When it loads more data there a some seemingly random instances where it throws one of two errors. 
After the first one nixview crashes completely the second one doen't have any obvious consequences.
 (going to push my branch soon and link to it)

Error 1:
#000: ../../../src/H5L.c line 813 in H5Lexists(): not a location
    major: Invalid arguments to routine
    minor: Inappropriate type
  #001: ../../../src/H5Gloc.c line 195 in H5G_loc(): invalid group ID
    major: Invalid arguments to routine
    minor: Bad value

and error 2:

HDF5-DIAG: Error detected in HDF5 (1.8.16) thread 140473211713280:
  #000: ../../../src/H5I.c line 1384 in H5Idec_ref(): can't decrement ID ref count
    major: Object atom
    minor: Unable to decrement reference count
  #001: ../../../src/H5I.c line 1491 in H5I_dec_app_ref(): can't decrement ID ref count
    major: Object atom
    minor: Unable to decrement reference count
  #002: ../../../src/H5I.c line 1421 in H5I_dec_ref(): can't locate ID
    major: Object atom
    minor: Unable to find atom information (already closed?)

**Comment by Nyxas** [comment]
So finally pushed it.

The errors occur getAxis() in the LoadingThread. (line 112)
But the function only gets copies of the members, so there should be, as far as i know, no way for the main thread to interfere with it during this function, except if they can't both read the file at the same time. 
https://github.com/Nyxas/NixView/blob/lineplotter_rework2/utils/loadthread.cpp

I built in a delay in run() before it starts and since then get no problems, but I can't say for sure if it's just very rare because it runs only rarely, or it is 'fixed' because the lineplotter doesn't access the DataArray anymore.     

And the lineplotter that controls the Thread:
https://github.com/Nyxas/NixView/blob/lineplotter_rework2/plotter/lineplotter.cpp

**Comment by Nyxas** [comment]
I think both threads call functions on the dimension of the array at the same time.
In loadthread during the getAxis() and in lineplotter during the calcStartExtent() (line 141) and checkForMoreData() (line 457).
I tested them and they also throw the same errors

**Comment by jgrewe** [comment]
Closing this for now: The current state is that concurrent access to the file should be avoided.
