### ISSUE TITLE
Contact information in the wiki is not up to date

### ISSUE THREAD

**Issue by delwen** [G-Node/nix#726]
https://github.com/G-Node/nix/wiki
For Christian and Adrian the link is broken

**Comment by gicmo** [comment]
Sounds good to me. Is there not a nix specific one? nix@gnode or something?

**Comment by achilleas-k** [comment]
I always forget which ones exist and which don't. I'll find out and update accordingly.

**Comment by jgrewe** [comment]
updated and done :) Thanks @delwen !
