### ISSUE TITLE
tagRefsHaveUnits is the same as tagUnitsMatchRefsUnits

### ISSUE THREAD

**Issue by hkchekc** [G-Node/nix#739]
https://github.com/G-Node/nix/blob/2e51fbaa0134b62b763dab871d4f2476a2017c92/src/valid/checks.cpp#L25

These two function is identical. It seems like the tagRefsHaveUnits should check only if the number of dimensions match the number of units.

**Comment by jgrewe** [comment]
good catch @hkchekc ! you are perfectly right, will be fixed soon!

**Comment by jgrewe** [comment]
closed via #736, thanks for reporting!
