### ISSUE TITLE
Reorganise documentation

### ISSUE THREAD

**Issue by achilleas-k** [G-Node/nix#790]
Documentation for NIX is scattered across several locations:
- [nixio.readthedocs.io](nixio.readthedocs.io): Contains tutorials and documentation automatically generated from the `docs/` directory in the repository.
- The GitHub Wiki contains (mostly) technical and developer documentation.
- http://g-node.github.io/nix/ mostly links to other pages (source repo, nixpy docs).

We also have demo repositories that contain helpful scripts and example use cases.

We should organise these, know what each one is for, link to each of them from the repository README interlink them all so that they can be easily discovered by users.

**Comment by achilleas-k** [comment]
Should check whether it's possible to combine the API docs with the tutorial examples and push them both to ReadTheDocs.

**Comment by jgrewe** [comment]
This has been done
