### ISSUE TITLE
Functions for Column Dimensions

### ISSUE THREAD

**Issue by hkchekc** [G-Node/nix#804]
related to #420, #748

I think with the Column Dimensions, there could be some links on the DataArray opject to the DataFrame such that when some part of the data in the DataArray is being printed or something, the related data in the DataFrame will also be shown

**Comment by jgrewe** [comment]
@hkchekc is this still an issue? Not sure, if I understand, though

**Comment by hkchekc** [comment]
@jgrewe I think not anymore an issue. Close?

**Comment by jgrewe** [comment]
Thanks @hkchekc, closing
